name = "GraphAnalyticsPlatform"
uuid = "12345678-1234-5678-1234-567812345678"
authors = ["Gabriel Demetrios Lafis"]
version = "1.0.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
